### ISSUE TITLE
How do you split the SportVU dataset?

### ISSUE THREAD

**Issue by NorthOcean** [noparkee/Deep-Learning#3]
Hi, I'm sorry to open an unrelated issue in this repository.

I find your issue in https://github.com/amazon-research/explainable-trajectory-prediction/issues/5.
The NBA SportVU dataset (https://github.com/linouk23/NBA-Player-Movements) contains about 700 JSON files, each of which is about 100M.

Therefore, I seek your help on how to split the dataset.
My email is xbh_hust@hust.edu.cn

Thanks again for your help.

**Comment by noparkee** [comment]
Hi!
I just followed the https://github.com/amazon-research/explainable-trajectory-prediction.
According to the [_explainable-trajectory-prediction/tools/prepare_data.py_](https://github.com/amazon-research/explainable-trajectory-prediction/blob/main/tools/prepare_data.py), they use only randomly selected 6000~7000 events then they split them into the train, val, and test. (0.7:0.09:0.21)

Was this answer helpful?

**Comment by NorthOcean** [comment]
Thanks for your help. I will have a try.
If you are interested in trajectory prediction, you may wish to take a look at our works, like CSCNet (https://www.sciencedirect.com/science/article/abs/pii/S0031320322000334), V^2-Net (https://github.com/cocoon2wong/Vertical).

Thanks again for your help.
